apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: tjkim251/hello-world:a9d58dd6010ebeb2cd52fabd2320c98f4076244c
        ports:
        - containerPort: 80

