name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master  # master 브랜치로 풀 리퀘스트 시 실행       

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build and Push Docker Image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ github.sha }}

    # 4. Update Kubernetes manifests
    - name: Update Kubernetes Deployment
      run: |
        sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ github.sha }}|g" k8s/deployment.yaml
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add k8s/deployment.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push

